-- DDL Exercicio_1_4

CREATE DATABASE Exercicio_1_4;


CREATE TABLE TipoPermissao
(
	IdTipoPermissao INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(25) NOT NULL UNIQUE
);


CREATE TABLE Usuario
(
	IdUsuario INT PRIMARY KEY IDENTITY,
	IdTipoPermissao INT FOREIGN KEY REFERENCES TipoPermissao(IdTipoPermissao),
	Nome VARCHAR(50) NOT NULL,
	Email VARCHAR(50) NOT NULL UNIQUE,
	Senha VARCHAR(20) NOT NULL
);



CREATE TABLE Artista
(
	IdArtista INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE Estilo
(
	IdEstilo INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(10) NOT NULL UNIQUE
);


CREATE TABLE Album
(
	IdAlbum INT PRIMARY KEY IDENTITY,
	IdArtista INT FOREIGN KEY REFERENCES Artista(IdArtista),
	Titulo VARCHAR(20) NOT NULL,
	DataLancamento DATE NOT NULL,
	Minutagem TIME NOT NULL,
	PodeSerVisualizado BIT NOT NULL
);


CREATE TABLE EstiloAlbum
(
	IdEstiloAlbum INT PRIMARY KEY IDENTITY,
	IdEstilo INT FOREIGN KEY REFERENCES Estilo(IdEstilo) NOT NULL,
	IdAlbum INT FOREIGN KEY REFERENCES Album(IdAlbum) NOT NULL,
);

CREATE TABLE Musica
(
	IdMusica INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(35) NOT NULL,
	Minutagem TIME NOT NULL
);

CREATE TABLE MusicaAlbum
(
	IdMusicaAlbum INT PRIMARY KEY IDENTITY,
	IdAlbum INT FOREIGN KEY REFERENCES Album(IdAlbum),
	IdMusica INT FOREIGN KEY REFERENCES Musica(IdMusica)
);