-- DDL: Criação


CREATE DATABASE Exercicio_2_2;

-- Entrar no banco de dados
USE Exercicio_2_2;

-- Criação de tabelas
CREATE TABLE Empresa
(
	IdEmpresa INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(100) NOT NULL,
	Cnpj VARCHAR(20) NOT NULL UNIQUE
);

CREATE TABLE Cliente
(
	IdCliente INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(60) NOT NULL,
	Cpf VARCHAR(25) NOT NULL UNIQUE,
	NumeroCelular VARCHAR(22) NOT NULL UNIQUE, 
);

CREATE TABLE Marca
(
	IdMarca INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(50) NOT NULL
);

CREATE TABLE Modelo
(
	IdModelo INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(20) NOT NULL
);


CREATE TABLE Veiculo
(
	IdVeiculo INT PRIMARY KEY IDENTITY,
	IdMarca INT FOREIGN KEY REFERENCES Marca(IdMarca) NOT NULL,
	IdModelo INT FOREIGN KEY REFERENCES Modelo(IdModelo) NOT NULL,
	IdEmpresa INT FOREIGN KEY REFERENCES Empresa(IdEmpresa) NOT NULL,
	Placa VARCHAR(10) NOT NULL UNIQUE
);

CREATE TABLE Aluguel
(
	IdAluguel INT PRIMARY KEY IDENTITY,
	IdCliente INT FOREIGN KEY REFERENCES Cliente(IdCliente) NOT NULL,
	IdVeiculo INT FOREIGN KEY REFERENCES Veiculo(IdVeiculo) NOT NULL,
	Codigo VARCHAR(40) NOT NULL UNIQUE,
	Duracao TIME NOT NULL,
	[Data] DATE NOT NULL
);