-- DDL: Criação

USE master;

CREATE DATABASE Exercicio_1_3;

-- Usar Entrar no banco criado
USE Exercicio_1_3;

-- Criar tabelas
CREATE TABLE Clinica
(
	IdClinica INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(50) NOT NULL,
	Endereco VARCHAR(65) NOT NULL UNIQUE,
	Telefone VARCHAR(22) NOT NULL UNIQUE
);

CREATE TABLE Veterinario
(
	IdVeterinario INT PRIMARY KEY IDENTITY,
	IdClinica INT FOREIGN KEY REFERENCES Clinica(IdClinica),
	Nome VARCHAR(50) NOT NULL,
	Expediente TIME NOT NULL
);

CREATE TABLE Atendimento
(
	IdAtendimento INT PRIMARY KEY IDENTITY,
	IdVeterinario INT FOREIGN KEY REFERENCES Veterinario(IdVeterinario),
	IdPet INT FOREIGN KEY REFERENCES Pet(IdPet),
	Descricao VARCHAR(MAX) NOT NULL,
	Data DATE NOT NULL
);

CREATE TABLE Tipo
(
	IdTipo INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(20) NOT NULL UNIQUE,
);

CREATE TABLE Raca
(
	IdRaca INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(20) NOT NULL UNIQUE
);

CREATE TABLE Pet
(
	IdPet INT PRIMARY KEY IDENTITY,
	IdTipo INT FOREIGN KEY REFERENCES Tipo(IdTipo),
	IdRaca INT FOREIGN KEY REFERENCES Raca(IdRaca),
	Nome VARCHAR(20) NOT NULL,
	DataNascimento DATE NOT NULL
);

CREATE TABLE Dono
(
	IdDono INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(50) NOT NULL,
);

CREATE TABLE DonoPet
(
	IdDonoPet INT PRIMARY KEY IDENTITY,
	IdDono INT FOREIGN KEY REFERENCES Dono(IdDono),
	IdPet INT FOREIGN KEY REFERENCES Pet(IdPet),
);